language: android
dist : trusty
sudo: true
android:
  components:
    - tools
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+' 
before_install:

  - sudo apt-get install ant
install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager --channel=3 --channel=1 "cmake;3.10.2.4988404"
  - echo y | sdkmanager "lldb;3.1"
before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle

script:
  # scripts excutes inside our repo directory on CI machine
  - export SAMPLE_CI_RESULT=0
  -  ./gradlew --no-daemon assembleDebug
